### ISSUE TITLE
Feature request (1800): restrict tile to company

### ISSUE THREAD

**Issue by Hawke** [freystef/Rails#7]
In _1800_ one of the private companies has a special tile which only it can use.

I was hoping to simply add a SpecialTileLay setup for it, but it seems that there is no way to restrict the tile like this -- any company is allowed to place the tile.

**Comment by erik-vos** [comment]
Alex,

I am no longer familiar enough with the code to provide a quick answer, 
but things you could try are:
- set the tile quantity to zero,
  or
- disallow the upgrade to this tile for all hexes (or even omit the 
  upgrade)

and in your code somehow override any checks that fail because of these 
settings. Probably you'll have to override OperatingRound.layTile() and 
OperatingRound.getSpecialTileLays() (or other methods called by these 
methods) in your OperatingRound_1800.

Erik

Op 26-10-2016 om 18:28 schreef Alex Mauer:

**Comment by neutronc** [comment]
Hi,

perhaps you can have a look at 18AL ? Theres a tile being linked to a private compan iirc.
Regards,
Martin

**Comment by ChrisTheCat** [comment]
Yes, it seems like the 18AL Lumber company (places tile in swamp) would
apply.

**Comment by erik-vos** [comment]
Ah yes, the Lumber Terminal! That one caused me quite some headaches to 
implement. Don't remember the code details, but in 18AL/TileSet.xml 
you'll find this:

```
<Tile id="0"><!-- Empty space -->
    <Upgrade id="7,8,9"/>
    <!--Upgrade id="445" hex="G2,M2,N5,O4,P5"/-->
</Tile>
```

in other words: just omit the regular upgrade rule.
Erik

Op 26-10-2016 om 20:37 schreef Dr. Martin Brumm:

**Comment by Hawke** [comment]
Thanks for the advice. Dropping it from the upgrade path was part of the key to prevent other companies from placing the tile (#800). Not sure why it still allows upgrading but doesn't allow placing on an entirely empty space. But I'll take it!

The lumber company in _18AL_ was very helpful for sure -- Although _1800_ is a little different in that this private company does not require that it be owned by another company in order to work.

Only problem I'm running into now is that the special tile is allowed to be placed even if the company is not connected to the hex. If I set the "connected" attribute to yes, then it doesn't allow placement at all.

**Comment by neutronc** [comment]
Hi Alex

The latter sounds like a bug.

I might check this the weekend after this if nobody beats me to that :)

Regards Martin

Gesendet mit der Telekom Mail App
http://www.t-online.de/service/redir/emailmobilapp_ios_smartphone_footerlink.htm

-----Original-Nachricht-----
Von: Alex Mauer <notifications@github.com <mailto:notifications@github.com> 

> Betreff: Re: [freystef/Rails] Feature request (1800): restrict tile to 
> company (#7)
> Datum: 27.10.2016, 18:29 Uhr
> An: freystef/Rails <Rails@noreply.github.com
> <mailto:Rails@noreply.github.com> >
> CC: Dr. Martin Brumm <dr.martin.brumm@t-online.de
> <mailto:dr.martin.brumm@t-online.de> >, Comment <
> comment@noreply.github.com mailto:comment@noreply.github.com >

Thanks for the advice. Dropping it from the upgrade path was part of the 
key to prevent other companies from placing the tile (#800). Not sure why 
it still allows upgrading but doesn't allow placing on an entirely empty 
space. But I'll take it!

The lumber company in 18AL was very helpful for sure -- Although 1800 is a 
little different in that this private company does not require that it be 
owned by another company in order to work.

Only problem I'm running into now is that the special tile is allowed to be 
placed even if the company is not connected to the hex. If I set the 
"connected" attribute to yes, then it doesn't allow placement at all.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
https://github.com/freystef/Rails/issues/7#issuecomment-256697309 , or 
mute the thread

**Comment by neutronc** [comment]
Btw there is a discussion list for stuff like this badend on the 
sourceforge repo.

Might catch even more attention.

Regards Martin

Gesendet mit der Telekom Mail App
http://www.t-online.de/service/redir/emailmobilapp_ios_smartphone_footerlink.htm

-----Original-Nachricht-----
Von: Alex Mauer <notifications@github.com <mailto:notifications@github.com> 

> Betreff: Re: [freystef/Rails] Feature request (1800): restrict tile to 
> company (#7)
> Datum: 27.10.2016, 18:29 Uhr
> An: freystef/Rails <Rails@noreply.github.com
> <mailto:Rails@noreply.github.com> >
> CC: Dr. Martin Brumm <dr.martin.brumm@t-online.de
> <mailto:dr.martin.brumm@t-online.de> >, Comment <
> comment@noreply.github.com mailto:comment@noreply.github.com >

Thanks for the advice. Dropping it from the upgrade path was part of the 
key to prevent other companies from placing the tile (#800). Not sure why 
it still allows upgrading but doesn't allow placing on an entirely empty 
space. But I'll take it!

The lumber company in 18AL was very helpful for sure -- Although 1800 is a 
little different in that this private company does not require that it be 
owned by another company in order to work.

Only problem I'm running into now is that the special tile is allowed to be 
placed even if the company is not connected to the hex. If I set the 
"connected" attribute to yes, then it doesn't allow placement at all.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
https://github.com/freystef/Rails/issues/7#issuecomment-256697309 , or 
mute the thread

**Comment by Hawke** [comment]
> Btw there is a discussion list for stuff like this badend on the
> sourceforge repo.

Thanks -- I had looked at the mailing lists linked on the main page and it looked like they were basically dead.
